<div ng-controller="addPackController">
    <form id="pack" action="" autocomplete="off">
        <p>Название стикер-пака</p>
        <input type="text" name="pack" 
            ng-model="pack"
            required ng-blur="createPack()" ng-focus="created = undefined">
            
        <p class="message" ng-show="created !== undefined">
            <span class="pack">{{pack}}</span> {{created? "pack was created": "pack was choosed"}}, now load the stickers! ح(◉ ⌣ ◉)づ
        </p>
    </form>
    <form id="stickers" action="" ng-show="created !== undefined">
        <p>Загрузите изображения для стикеров (формат .png)</p>
        <input type="file" name="img[]" 
            multiple required 
            accept="image/png"
            onchange="angular.element(this).scope().uploadStickers(this)">
        <p id="loading"></p>
    </form>
    <div id="captcha" style="display: none;">
        <img>
        <form action="">
            <input type="text" name="captcha" required>
            <input type="submit" value="Check">
        </form>
    </div>
</div>