<div ng-controller="enterController">
    <? if($this->session->has("loggedIn")): ?>
        <p>Email: <?= $this->session->get("email");?></p>
        <p>User Id: <?= $this->session->get("user_id");?></p>
        <a href="/index/logOut">
            <button>Выйти</button>
        </a>
    <? else: ?>
        <a href="https://oauth.vk.com/authorize?client_id=6396314&display=page&redirect_uri=http://rurka.loc/vk/token&scope=docs,email&response_type=code&v=5.73">
            <button>Войти ВК</button>
        </a>
    <? endif; ?>
</div>
